### ISSUE TITLE
Pod::DSLError

### ISSUE THREAD

**Issue by pepasibble** [Subito-it/PodBuilder#50] opened 2021-10-27 18:45 UTC
Hello,

I'm running into a problem when trying to use pod_builder with a newly created React Native app:

```
$ pod_builder build_all
Loading Podfile
Pod::DSLError
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:335:in `rescue in block in from_ruby'
	/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:329:in `block in from_ruby'
	/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
	/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:50:in `initialize'
	/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:327:in `new'
	/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:327:in `from_ruby'
	/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:293:in `from_file'
	/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:205:in `podfile'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/lib/pod_builder/analyze.rb:24:in `block in installer_at'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/lib/pod_builder/analyze.rb:22:in `chdir'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/lib/pod_builder/analyze.rb:22:in `installer_at'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/lib/pod_builder/command/build.rb:24:in `call'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/lib/pod_builder/command/build_all.rb:11:in `call'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/exe/pod_builder:368:in `block in parse_commandline'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/exe/pod_builder:367:in `each'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/exe/pod_builder:367:in `parse_commandline'
	/Library/Ruby/Gems/2.6.0/gems/pod-builder-4.2.0/exe/pod_builder:383:in `<top (required)>'
	/usr/local/bin/pod_builder:23:in `load'
	/usr/local/bin/pod_builder:23:in `<main>'


Command failed!
```

Where would I add some debugging statements to print out which line in the Podfile is causing the DSL error?

**Comment by aminbenarieb** [comment] 2021-11-04 08:44
Save thing after checking and installing pods from other machine

**Comment by emartinson** [comment] 2021-11-15 08:02
Same for me at
Pod: 1.11.2
OS: macOS Big Sur 11.6

**Comment by tcamin** [comment] 2021-11-17 11:23
Closing since it's a duplicate of #47, see https://github.com/Subito-it/PodBuilder/issues/47#issuecomment-971481636

**Closed by tcamin** 2021-11-17 11:23 UTC
