### ISSUE TITLE
tmp/pod_builder/pod_builder.err does not exist.

### ISSUE THREAD

**Issue by mm44m6** [Subito-it/PodBuilder#11] opened 2020-09-01 15:12 UTC
Hi, I'm trying to use pod builder inside an iOS project. it seems to build the dependency just fine when I run `pod_builder build <podName>` but when it starts installing all the project's dependencies, it throws `Command failed, check /tmp/pod_builder/pod_builder.err!`, the only problem is that `/tmp/pod_builder/pod_builder.err` is not actually created, which means I have no idea what might be wrong with my implementation. 😞 
is there any other way to access this error log?

**Comment by tcamin** [comment] 2020-09-03 10:39
Could you try with the latest beta (`gem install --pre`)?

**Comment by dcristolovean** [comment] 2020-09-21 11:42
I tried to run pod_builder build all again today (after it worked nicely last time, prebuilt quite a few of firebase's pods) and I'm getting now the same "error". 
I just installed the last beta, same thing.   there is no pod_builder in /tmp or any other error file.

BEFORE last beta:

pod_builder build_all
Loading Podfile
Updating local specs repositories
  $ /usr/bin/git -C /Users/*/.cocoapods/repos/cocoapods fetch origin --progress
  remote: Enumerating objects: 15, done.        
  remote: Counting objects: 100% (15/15), done.        
  remote: Compressing objects: 100% (9/9), done.        
  remote: Total 9 (delta 6), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     f5ebb2afc8dd..050149e6441a  master     -> origin/master
  $ /usr/bin/git -C /Users/*/.cocoapods/repos/cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/*/.cocoapods/repos/cocoapods reset --hard origin/master
  HEAD is now at 050149e6441a [Add] NFCPassportReader 1.0.12
Analyzing dependencies

Command failed, check /tmp/pod_builder/pod_builder.err!

WITH the last beta:

pod_builder build_all
Loading Podfile
Updating local specs repositories
Analyzing dependencies


Command failed, check /tmp/pod_builder/pod_builder.err!

**Comment by tcamin** [comment] 2020-09-21 11:45
Did you try building with -d flag?

**Comment by dcristolovean** [comment] 2020-09-21 11:51
yes, same thing. Although there's a PodBuilder.lock file in /tmp.   But it gets deleted when the error comes up and there's nothing else in there.

**Comment by dcristolovean** [comment] 2020-09-21 15:25
any idea what we can do, at least to see what the problem is ?

**Comment by tcamin** [comment] 2020-09-21 16:06
> s, same thing. Although there's a PodBuilder.lock file in /tmp. But it gets deleted when the error comes up and there's nothing else in there.

That's sad :-( we are using beta 26 and everything has been working well.

You get no other error? Did you try to deintegrate and reintegrate PodBuilder?

If that doesn't work either, I can only suggest to temporarily rollback to the previous version that was working for you. I made a large amount of changes lately so something might have gone wrong sorry about that

**Comment by dcristolovean** [comment] 2020-09-21 17:04
weird thing is that the version I had worked...  then i didnt use it for a week or so and today, running a build all resulted in that hidden error.
Maybe you can print the error in the output, instead of in that file ? with an extra option to toggle this on/off ?

**Comment by tcamin** [comment] 2020-09-21 17:22
> weird thing is that the version I had worked... then i didnt use it for a week or so and today, running a build all resulted in that hidden error.

That is unexpected. However you can modify the source code yourself since ruby is an interpreted language. 

Depending on how you install gems (check `gem environment`) you'll find files in different locations but just as an example if you user rbenv, edit ~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/pod-builder-2.0.0.beta.26/exe/pod_builder

add `puts error` at line 377.

**Comment by dcristolovean** [comment] 2020-09-22 07:38
Thanks for the info !
I found the error, damn it, I removed some targets a few days ago, but my Pod file was still using

target 'old' do
  myPods
end 

My bad, good thing I saw the error now.

**Comment by tcamin** [comment] 2020-09-22 09:55
Wasn't the problem with the missing target reported anyhow in PodBuilder's output?

**Comment by dcristolovean** [comment] 2020-09-22 11:34
no, not until I added the puts error.

**Comment by tcamin** [comment] 2020-09-22 17:25
Ok, I'm pretty confident this has been sorted out in next beta.

**Comment by tcamin** [comment] 2020-09-23 12:58
@dcristolovean Could you try to replicate the problem you had the other day with the missing targets to see if the latest beta properly prints out the error?

If it's fixed I could close this issue

**Comment by dcristolovean** [comment] 2020-09-24 05:38
Yes, all good now, I'm getting the big red ugly error about a missing target directly in the output.
Thanks a lot for the promptitude with answers and fixes!

**Closed** 2020-09-24 05:51 UTC
