### ISSUE TITLE
Debugging while using prebuilt frameworks.

### ISSUE THREAD

**Issue by tareksabry1337** [Subito-it/PodBuilder#12] opened 2020-09-03 07:26 UTC
I'm having an issue after integrating pod_builder into my project that I can no longer debug my code it throws
`Couldn't IRGen expression, no additional error` when I try to do "po someVariable" on the console

I also tried the sample project but no avail it's the same.

Am I doing something wrong ? Or is this supposed to be run on CI environments only ?

**Comment by tcamin** [comment] 2020-09-03 07:30
Which version of PodBuilder are you using?

**Comment by tareksabry1337** [comment] 2020-09-03 07:31
The latest 1.9.4

**Comment by tcamin** [comment] 2020-09-03 07:53
Are you able to reproduce this on a minimal example project that can be shared?

**Comment by tcamin** [comment] 2020-09-03 07:59
Could you try with the latest beta? `gem install pod-builder --pre`

**Comment by tareksabry1337** [comment] 2020-09-03 08:03
The beta version does not init on the sample project and throws `xcworkspace not found!` even though I'm at the project folder where .xcworkspace file exists.

<img width="1508" alt="Screen Shot 2020-09-03 at 10 02 59 AM" src="https://user-images.githubusercontent.com/45688300/92088043-a70d4f00-edcc-11ea-9775-0f5fa58dde5b.png">

**Comment by tcamin** [comment] 2020-09-03 10:37
I made a few changes, tried on beta 23 and it seemed to work ok.

<img width="1156" alt="Screenshot 2020-09-03 at 11 58 32" src="https://user-images.githubusercontent.com/875025/92104805-28bba780-ede2-11ea-834b-2f38c31c98cc.png">

**Comment by tareksabry1337** [comment] 2020-09-03 10:41
Unfortunately I am still unable to init it on the example project using the beta version (updated to beta 23)

<img width="1545" alt="Screen Shot 2020-09-03 at 12 40 57 PM" src="https://user-images.githubusercontent.com/45688300/92105169-b8f9ec80-ede2-11ea-882f-d2e74c02f6cc.png">

**Comment by tcamin** [comment] 2020-09-03 11:07
Forgot to mention that you need to checkout the `deterministic_build` branch. BTW the Example project is already inited so you just need to run `pod_builder build_all`.

**Comment by tareksabry1337** [comment] 2020-09-03 11:17
After checking out deterministic_build and running `pod_builder build_all` the result is as below.

<img width="1603" alt="Screen Shot 2020-09-03 at 1 17 04 PM" src="https://user-images.githubusercontent.com/45688300/92108480-c4034b80-ede7-11ea-92e0-986c3b089f26.png">

**Comment by tcamin** [comment] 2020-09-03 11:28
Bear with me one more time 😂. Pull and try again

**Comment by tareksabry1337** [comment] 2020-09-03 11:40
The command was taking unusually long time, I though it was because of all the pods installed. I remove all of them and installed only Alamofire to test faster but it has been a while and it's stuck on "Downloading Pods source code"

<img width="1600" alt="Screen Shot 2020-09-03 at 1 39 05 PM" src="https://user-images.githubusercontent.com/45688300/92110345-d6cb4f80-edea-11ea-86a1-bba1e14087b1.png">

I'm leaving it until it's done nonetheless.

**Comment by tcamin** [comment] 2020-09-03 11:41
Did you remove the entries from the PodBuilder/Podfile?

**Comment by tareksabry1337** [comment] 2020-09-03 11:44
Nope, I didn't. Now I did and it's done.
Will report back once it's done.

**Comment by tareksabry1337** [comment] 2020-09-03 11:45
Everything is working as expected, except that I'm still having the same exact error.

<img width="889" alt="Screen Shot 2020-09-03 at 1 45 35 PM" src="https://user-images.githubusercontent.com/45688300/92110912-bf409680-edeb-11ea-9bc1-f33041338681.png">

**Comment by tcamin** [comment] 2020-09-03 11:46
That's the main Podfile, the other one is autogenerated and should be generally not be modified manually (as changes will be overwritten)

**Comment by tcamin** [comment] 2020-09-03 11:49
That is kind of weird because it is working fine on my side and I have your same setup: Xcode 11.5 and CP 1.9.3.

Try the following
1. delete derived data and run again
2. delete the dSYM folder, delete derived data and run again.

**Comment by tareksabry1337** [comment] 2020-09-03 11:54
Wow, can't believe that actually deleting derived data worked lol.
Thanks for all of your hard work on this.

Just one last question, is the newest beta intended to fix Firebase installation issues from https://github.com/Subito-it/PodBuilder/issues/8 ?

**Comment by tcamin** [comment] 2020-09-03 11:59
🎉🎉🎉

The OP seems not to have solved the issue however we are using the beta on a very large project that uses Firebase and it works on our side.

The example project integrates firebase as in #8. It compiles fine here but it will take a significant amount of time (depends on the hardware) because it is building the framework with several slices (that's the benefit of PB: build once for all archs).

If you try it and run into troubles reply to that issue or open a new one. 

Closing this one for the moment, thanks for the feedback so far.

**Closed by tcamin** 2020-09-03 11:59 UTC

**Comment by tareksabry1337** [comment] 2020-09-03 12:24
@tcamin I have a quick question regarding this issue, so it turns out that deleting derived data isn't the issue but the dSYM folder under PodBuilder folder is actually what resolves that, so my question is how does this affect my project when I delete the dSYM folder ?

**Comment by tcamin** [comment] 2020-09-03 12:33
It is strange because on my side it is working fine even with dSYM folder. Nonetheless I sugggested to delete the folder because I read about the issue here: https://steipete.com/posts/couldnt-irgen-expression

dSYM bundles contain debug information that is used to symbolicate your application's frames, that is translating binary memory addresses back to your source come classes and methods. You should send these files to e.g to Firebase so that your crash report get properly symbolicated. They are also used for example when running Instruments.

You do not need dSYM to run/debug your project but you can't get rid of them because they are essential to get proper information out of crashes.

**Comment by tcamin** [comment] 2020-09-03 12:35
We don't have the `Couldn't IRGen expression, no additional error` issue so I would suggest to investigate if it somehow related to something in your setup.

**Comment by tareksabry1337** [comment] 2020-09-03 12:38
I'm certainly convinced it's something on my setup, but I've no idea what's wrong I'm coming from a neighbor plugin `cocoapods-binary` I had the exact same issue there but I thought because that plugin is outdated and is no longer maintained but boy oh boy I was wrong. I'll try to do a fresh installation of macOS / Xcode maybe I messed something up.

**Comment by tcamin** [comment] 2020-09-03 12:45
Does this happen both on device and simulator?

**Comment by tareksabry1337** [comment] 2020-09-03 12:52
Yep, just tried both and I'm getting the same error.
What's even more interesting that I have a mac mini that has the exact same environment Xcode 11.5, Cocoapods 1.9.3 and it has the same exact issue.

At this point I'm not really sure what's causing it.

**Comment by tcamin** [comment] 2020-09-03 13:31
What if you exclude the entire project folder from Spotlight?

**Comment by tareksabry1337** [comment] 2020-09-03 13:35
What do you mean by excluding a project from Spotlight ? I'm not really aware.

**Comment by tcamin** [comment] 2020-09-03 13:36
Remove the project folder from Spotilight indexing

<img width="663" alt="Screenshot 2020-09-03 at 15 36 45" src="https://user-images.githubusercontent.com/875025/92122050-477a6800-edfb-11ea-98c7-198ee32f57b6.png">

**Comment by tcamin** [comment] 2020-09-03 13:40
Alternatively and more interestingly you could modify the PodBuilder.json file by adding the `build_settings_overrides` key as follows

```
"build_settings_overrides": {
    "OTHER_SWIFT_FLAGS": "$(inherited) -Xfrontend -no-serialize-debugging-options"
}
```

I didn't try myself. If you try let me know.

**Comment by tareksabry1337** [comment] 2020-09-03 13:42
What kind of black magic is this ? Excluding the folder from Spotlight works even with dSYM files !
Can you explain how does excluding folder from spotlight help ?

**Comment by tcamin** [comment] 2020-09-03 13:46
Because lldb uses spotlight to find dSYMs which are causing the issue. Good it works but it probably won't symbolicate instrument sessions. I would suggest to try the -no-serialize-debugging-options alternative which if it works should be more solid.

**Comment by tareksabry1337** [comment] 2020-09-03 13:52
No avail from `"OTHER_SWIFT_FLAGS": "$(inherited) -Xfrontend -no-serialize-debugging-options"` I guess I'll have to live with Spotlight off and enable it when needed 😂

**Comment by tcamin** [comment] 2020-09-03 14:25
I managed to reproduce it.

Apparently adding an Objective-C file to the project (together with the bridging headers) seems to workaround the issue. I updated the sample project accordingly and was able to print variables.

**Comment by tareksabry1337** [comment] 2020-09-03 14:31
Yep it works, even though it's "hacky" but this is better than both Spotlight indexing, slow build times combined.

<img width="609" alt="Screen Shot 2020-09-03 at 4 31 01 PM" src="https://user-images.githubusercontent.com/45688300/92128613-dccd2a80-ee02-11ea-9ce7-5a8098b25e39.png">

**Comment by tareksabry1337** [comment] 2020-09-03 14:33
I'm curious what are the side effects of doing this ?

**Comment by tcamin** [comment] 2020-09-03 15:12
Not that I'm aware of.
